set working-directory := '../..'

image := "accounts:latest"
deployment := "accounts"

test:
    cd services/accounts && PATH="/opt/homebrew/opt/ruby/bin:$PATH" bundle exec ruby test/app_test.rb

build:
    eval $(minikube -p minikube docker-env) && \
    docker build -t {{image}} services/accounts/

deploy:
    kubectl delete deployment {{deployment}} --ignore-not-found=true
    kubectl apply -f k8s/accounts.yaml

rebuild: test build deploy
    kubectl rollout status deployment/{{deployment}} --timeout=60s
