set working-directory := '../..'

image := "accounts:latest"
deployment := "accounts"

build:
    eval $(minikube -p minikube docker-env) && \
    docker build -t {{image}} services/accounts/

deploy:
    kubectl delete deployment {{deployment}} --ignore-not-found=true
    kubectl apply -f k8s/accounts.yaml

rebuild: build deploy
    kubectl rollout status deployment/{{deployment}} --timeout=60s
