set working-directory := '../..'

image := "presence:latest"
deployment := "presence"

test:
    cd services/presence && go test ./...

build:
    eval $(minikube -p minikube docker-env) && \
    docker build -t {{image}} services/presence/

deploy:
    kubectl delete deployment {{deployment}} --ignore-not-found=true
    kubectl apply -f k8s/presence.yaml

rebuild: test build deploy
    kubectl rollout status deployment/{{deployment}} --timeout=60s
